### ISSUE TITLE
  File "/home/pi/PiVT/pivtgapless.py", line 90, in __init__

### ISSUE THREAD

**Issue by revelator0815** [ystv/PiVT#10]
Hi got this error on a clean new install any ideas?

2014-06-01 18:22:33,133:INFO:Getting playlist item durations...
2014-06-01 18:22:37,409:ERROR:Failed to load the first two videos. Shutting down
2014-06-01 18:22:37,412:ERROR:Startup failed! This is definitely not good!
Traceback (most recent call last):
  File "/home/pi/PiVT/pivtgapless.py", line 90, in **init**
    raise Exception
Exception
2014-06-01 18:22:37,419:ERROR:Exception caught, shutting down

**Comment by samdbmg** [comment]
Hi, 

Sorry its taken me so long to get back to you. I'm in the last
few days of deadlines for my degree at the moment, so I'll take a look
at this towards the end of this week if that's OK. Could you send me
your config.yaml and the command line you used to start PiVT? I suspect
there is a problem somewhere in the file paths. 

Sam 

On 01.06.2014
19:25, revelator0815 wrote: 

> Hi got this error on a clean new install
> any ideas? 
> 
> 2014-06-01 18:22:33,133:INFO:Getting playlist item
> durations...
> 2014-06-01 18:22:37,409:ERROR:Failed to load the first
> two videos. Shutting down
> 2014-06-01 18:22:37,412:ERROR:Startup
> failed! This is definitely not good!
> Traceback (most recent call
> last):
> File "/home/pi/PiVT/pivtgapless.py", line 90, in INIT
> raise
> Exception
> Exception
> 2014-06-01 18:22:37,419:ERROR:Exception caught,
> shutting down 
> 
> ## 
> 
> Reply to this email directly or view it on
> GitHub [1].

## Links:

[1] https://github.com/YSTV/PiVT/issues/10

**Comment by revelator0815** [comment]
Hey no problem im on  holidays right now so no trouble i reply when im home again Thanks so long

Von Samsung Mobile gesendet

-------- Ursprüngliche Nachricht --------
Von: Sam Nicholson notifications@github.com 
Datum: 09.06.2014  18:54  (GMT+01:00) 
An: YSTV/PiVT PiVT@noreply.github.com 
Cc: revelator0815 david@basketball-stream.de 
Betreff: Re: [PiVT]   File "/home/pi/PiVT/pivtgapless.py", line 90, in
  **init** (#10) 

Hi, 

Sorry its taken me so long to get back to you. I'm in the last
few days of deadlines for my degree at the moment, so I'll take a look
at this towards the end of this week if that's OK. Could you send me
your config.yaml and the command line you used to start PiVT? I suspect
there is a problem somewhere in the file paths. 

Sam 

On 01.06.2014
19:25, revelator0815 wrote: 

> Hi got this error on a clean new install
> any ideas? 
> 
> 2014-06-01 18:22:33,133:INFO:Getting playlist item
> durations...
> 2014-06-01 18:22:37,409:ERROR:Failed to load the first
> two videos. Shutting down
> 2014-06-01 18:22:37,412:ERROR:Startup
> failed! This is definitely not good!
> Traceback (most recent call
> last):
> File "/home/pi/PiVT/pivtgapless.py", line 90, in INIT
> raise
> Exception
> Exception
> 2014-06-01 18:22:37,419:ERROR:Exception caught,
> shutting down 
> 
> ## 
> 
> Reply to this email directly or view it on
> GitHub [1].

## Links:

[1] https://github.com/YSTV/PiVT/issues/10

**Comment by samdbmg** [comment]
I've managed to reproduce this one and I think I've fixed it in 84ddad5. If this is still a problem with the new version can you re-open the ticket?
