### ISSUE TITLE
Switching playback between mp4 and mov files

### ISSUE THREAD

**Issue by peskdale** [ystv/PiVT#5]
When playing an mp4 file, then playing a mov file while the mp4 is still running (or vice verse) causes playback issues. Stopping and restarting the file resolves this, but is impractical for panicked VT ops when mistakes are made.

**Comment by rrah** [comment]
I've had a look at this (admittedly on a Pi 3) and can't seem to reproduce. Would you be able to provide two files which can reproduce this issue?

**Comment by peskdale** [comment]
Given I filed this two years ago, and don't even remember the use case, I honestly can't provide files. Plus there's been a lot of commits since which may have stabilised it.

This was a month after HD upgrade, and @samdnic has tweaked a lot since. So issue may not even be present anymore.
