### ISSUE TITLE
shared libriaries?

### ISSUE THREAD

**Issue by kornerb** [ystv/PiVT#6]
Hi, 

I am fairly new to raspberry pi and linux in general. I really want to run the PiVT Server. I downloaded the binaries, but every time I go to run ./PiVT i get 
error while loading shared libraries: libboost_system.so.1.49.0: cannot open shared object file: No such file or directory.

Any help would be appreciated.

Thanks,

**Comment by samdbmg** [comment]
Hi,

That problem arises because PiVT uses a different version of Boost than ships with Raspbian.
Something like
    sudo apt-get install libboost1.49-dev
should install the missing dependencies.

However, PiVT was heavily rewritten over Christmas, which I should be putting up here in a week or so and won't suffer from these sorts of problems anymore, so it might be worth waiting on that.

Thanks,
Sam

**Comment by kornerb** [comment]
Excellent, I look forward to the new build! Please let me know when it's ready.

**Comment by samdbmg** [comment]
Ok, version 2 is up, and there's a new version of the client at https://github.com/YSTV/PiVTDesktop (or http://ystv.co.uk/static/downloads/PiVTDesktopSetup.exe)
I'll close this issue for now, let me know if you run into any problems.

**Comment by kornerb** [comment]
Thanks samdnic! Before I go and install this does it have any dependencies I need to know about? like boost or anything? I am going to put it on a clean/fresh raspian install.

**Comment by samdbmg** [comment]
It needs OMXPlayer (I think that's on default raspbian) along with python-pexpect and python-yaml which you should be able to install with apt-get. Let me know if that doesn't work and I'll test it myself on fresh Raspbian and update the instructions.

**Comment by deedos** [comment]
Hi sam. Thanks for the quick response. Yes, I got all requisites (python
yaml and python pexpect) installed and omxplayer  working.

Thanks
Em 18/01/2014 12:27, "Sam Nicholson" notifications@github.com escreveu:
