### ISSUE TITLE
ERROR:Startup failed! This is definitely not good!

### ISSUE THREAD

**Issue by deedos** [ystv/PiVT#8]
python PiVT.py --videofolder videos --config config.yaml

getting:

2014-01-17 17:39:52,344:INFO:PiVT starting up
2014-01-17 17:39:52,526:INFO:Setting up logging to pivtlog.log
2014-01-17 17:39:52,530:INFO:Configuration loaded
2014-01-17 17:39:52,534:INFO:Getting playlist item durations...
2014-01-17 17:39:52,730:ERROR:Startup failed! This is definitely not good!
Traceback (most recent call last):
  File "/home/pi/src/PiVT/pivtgapless.py", line 77, in **init**
    self._playing = self._load_internal(self._playlist[0][0],
IndexError: list index out of range
Traceback (most recent call last):
  File "PiVT.py", line 186, in <module>
    main()
  File "PiVT.py", line 143, in main
    player = PiVTGaplessVideo(playlist, videofolder, omxcommands, omxpath, cleanloop)
  File "/home/pi/src/PiVT/pivtgapless.py", line 94, in __init__
    raise Exception
Exception

What shuld I do ?

**Comment by kornerb** [comment]
I got the same error.

**Comment by samdbmg** [comment]
This happens because either no items in the playlist could be opened, or if there is no playlist, the stopvideo could not be played (due to permissions, non-existence or similar). 
Something has to be playing all the time, so when not using a playlist this is the stopvideo, in YSTV's case a spinning logo, which also helps prove PiVT is up and running.
I've added a more helpful error message when this occurs now and added a note in the readme about having a stopvideo or playlist items.
Let me know if that fixes the issue.

**Comment by kornerb** [comment]
Thanks, I did finally edit the config file and it worked for me. However, I thought the seemless looping was included with you install...:( I have tried to compile stewiem's version of omxplayer at least 5 times with no sucess. Guess I will try for 6. Why can't someone just make a binary for it?

**Comment by samdbmg** [comment]
Try http://samn.co.uk/dl/omx_seamless_loop.tar.gz which is the build I used - you might need to edit the omxplayer script inside to make it use the right binary and libraries

**Comment by kornerb** [comment]
Does that one at Samn.co.uk have to be compiled as well? I am having the same problem. with the huceke one I do the prepare-native-raspbian script, them make ffmpeg make. I get some errors at the the end of the make ffmpeg make but they don't look like anything fatal. Then I try to run ./omxplayer and no --loop option is available.
I am getting extremely frustrated at this point.

**Comment by samdbmg** [comment]
Oops, looks like that wasn't the built copy - I've updated the link with 
the correct file

**Comment by kornerb** [comment]
SUCCESS!! Excellent. Thank you very much.

**Comment by kornerb** [comment]
Not sure if this the appropriate place to post a request, but it would be great if there was an option in the client to 'seamless' loop one of the videos in the playlist. 
It seems to me that this could easily be accomplished by disabling the 'stopvideo' and adding the --loop to the omxargs. The problem I am having is that PiVT keeps trying to play the stopvideo at the same time. So the whole thing struggles and eventually the machine needs to be power cycled.
My application calls for multiple seamless looping videos, that can be triggered manually.

**Comment by deedos** [comment]
Hi. @kornerb What config and command line options did you use to suceed ? I  do not know what I 'm missing..
thanks in advance

**Comment by samdbmg** [comment]
@kornerb I've opened https://github.com/YSTV/PiVTDesktop/issues/1 for that suggestion

**Comment by kornerb** [comment]
@deedos
can you send me a copy of your config.yaml? It might be easier that way. you can send it to brian.korner@gmail.com

**Comment by kornerb** [comment]
@samdnic, thanks! That would be a really cool function.

**Comment by deedos** [comment]
@samdnic I ´m struglling and getting the 

ERROR:Unable to read the stopvideo or any playlist items. Shutting down
2014-01-22 20:51:59,321:ERROR:Exception caught, shutting down 

with all possible combination of config , omxplayer binary and command line options..

The video files (both in playlists and/or stopvideo) are playing fine with omxplayer.

thanks in advance

**Comment by samdbmg** [comment]
Hi @deedos 
Could you open another issue and include a copy of your config.yaml and I'll take a look?
